### ISSUE TITLE
URI contains hostname and protocol

### ISSUE THREAD

**Issue by jpstotz** [rburgst/okhttp-digest#10]
I tried your digest authenticator, however the authentication always fails. From my understanding the bug is in DigestAuthenticator line 332:

	if (qop == QOP_AUTH) {
				// Method ":" digest-uri-value
				a2 = method + ':' + uri; // <-- here

The value uri is at runtime a full URL like `http://example.org/path` - however the request Uri used by OkHttp in the HTTP request (first line) is `/path` (no host and no protocol). I have read that fully qualified uris including protocol and host are allowed as request line, however from my knowledge the common style is to send only the path and use the Host field instead in the request.

In rfc2617 I found the following statement:
>The authenticating server must assure that the resource designated by the "uri" directive is the same as the resource specified in the Request-Line; if they are not, the server SHOULD return a 400 Bad  Request error.

**Comment by rburgst** [comment]
Hm, this code has been working with a bunch of different servers. Did you try out your approach and did it work for a specific server where the full URI would not?

Also note that the passage in the RFC further reads

> The "Method" value is the HTTP request method as specified in section
>    5.1.1 of [2]. The "request-uri" value is the Request-URI from the
>    request line as specified in section 5.1.2 of [2]. This may be "*",
>    an "**absoluteURL*" or an "abs_path" as specified in section 5.1.2 of
>    [2], but it MUST agree with the Request-URI. In particular, it MUST
>    be an "absoluteURL" if the Request-URI is an "absoluteURL". The
>    "cnonce-value" is an optional  client-chosen value whose purpose is
>    to foil chosen plaintext attacks.

**Comment by jpstotz** [comment]
I changed your code the way I suggested and it works now for me. 

Please note: If you use the absolute or relative uri is not up to you. OkHttp (or the underlaying HTTP implementation) is the one who decides:

See for example the following HTTP request as captured by Wireshark:

	POST /path HTTP/1.1
	Content-Type: text/xml; charset=utf-8
	Content-Length: 265
	Host: example.org
	Connection: Keep-Alive
	Accept-Encoding: gzip
	User-Agent: okhttp/3.2.0

	<xml>...</xml>

The first line of an HTTP request is known as "request line": `POST /path HTTP/1.1`.
It contains the request-method `POST`, the request-uri `/path` and the HTTP protocol `HTTP/1.1`. 

Therefore from my understanding of the rfc you have to use this value and OkHttp uses the relative uri.

**Comment by rburgst** [comment]
I know that the first line needs to be relative. This is required. However the uri parameters is a totally different matter. I will double check with the Apache implementation and look for guidance there.


Am 20. Mai 2016, 20:10 +0200 schrieb Jan S.<notifications@github.com>:
