### ISSUE TITLE
Multiple retries with invalid password

### ISSUE THREAD

**Issue by glenharris** [rburgst/okhttp-digest#12]
Hi there,

I think that the fix for issue #8 may have introduced a bug when connecting with an *incorrect* password.  I am talking to a third-party server, and every time I attempt to talk to it, it gives me back a unique nonce.

If I attempt to connect to the server using an invalid password, I get a 401 response, which contains a new WWW-Authenticate header (with a new nonce).  This means that the new function havePreviousDigestAuthorizationWithSameNonce() is returning true, and so we keep retrying the same request again and again (I suspect eventually we will hit the 20 retries limit, but I dont have the patience).

Anyway, I am a HTTP Digest newbie, but my understanding is that the actual fix for #8 may have worked better if it looked for the 'stale="TRUE"' flag (and then verified that it has in fact received a new nonce to replace the stale one).

I have played around with this and seem to get the correct results but I am unable to test with a server that returns stale values, so I don't have a lot of confidence in my fix for the general case.  Are you interested in looking at a patch or pull request to see what I mean?

Cheers,

Glen.

**Comment by glenharris** [comment]
Sorry, I meant that havePreviousDigestAuthorizationWithSameNonce() returns false!

**Comment by rburgst** [comment]
I am certainly interested, maybe @N4zroth can tell us what server he is using and how to replicate the stale nonce.

**Comment by glenharris** [comment]
Sorry, I am new to github, so I am sure there is a better way of sending a patch, but the issue web interface would only let me attach a .zip.  I have tried to keep the same coding style, but feel free to improve the logic.  Let me know what you think.

[stale_nonce.diff.zip](https://github.com/rburgst/okhttp-digest/files/306142/stale_nonce.diff.zip)

**Comment by rburgst** [comment]
thanks a lot for the patch. In principle it looks good. Could you be so good to add/update the tests?

**Comment by rburgst** [comment]
I have tested the patch and IMHO it is not correct. It tries to read the stale parameter from the REQUEST rather than the RESPONSE.

```java
 final String previousAuthorizationHeader = previousRequest.header("Authorization");

        if (previousAuthorizationHeader != null && previousAuthorizationHeader.startsWith("Digest")) {
            // check if the previous nonce is the same as the current nonce
            Map<String, String> previousParameters = new HashMap<String, String>();
            parseChallenge(previousAuthorizationHeader, 7, previousAuthorizationHeader.length() - 7, previousParameters);
            final String previousStale = previousParameters.get("stale");
            if (previousStale != null && previousStale.toLowerCase().equals("true")) {
                // we should have been given a new nonce to recompute with, in which case we should not fail
                // the authorization
                final String previousNonce = previousParameters.get("nonce");
                if (!nonce.equals(previousNonce)) {
                    // We have been given a new nonce, so try recomputing our Digest.
                    // Note that there is a potential infinite loop if the server keeps giving us a new nonce
                    // each time, however it would also have to give us the 'stale' flag so I think this is pretty
                    // unlikely
                    return false;
                }
            }
```

My original code was only trying to figure out whether the previous request had a nonce, however, you now want to check the previous client nonce (from the request) and the stale header from the server response.

FYI, I started with the following tests, currently one of them fails with your code:

```java

    @Test
    public void testAuthenticate_withDifferentButNotStaleNonce_shouldNotRetry() throws IOException {
        // given
        Request dummyRequest = new Request.Builder()
                .url("http://www.google.com")
                .header("Authorization", "Digest username=\"user1\", realm=\"myrealm\", nonce=\"AAAAAAA\", uri=\"/\", response=\"[0-9a-f]+\", qop=auth, nc=00000001, cnonce=\"[0-9a-f]+\", algorithm=MD5")
                .get()
                .build();
        Response response = new Response.Builder()
                .request(dummyRequest)
                .protocol(Protocol.HTTP_1_1)
                .code(401)
                .addHeader("WWW-Authenticate",
                        "Digest realm=\"myrealm\", nonce=\"BBBBBB\", algorithm=MD5, qop=\"auth\"")
                .addHeader("WWW-Authenticate", "Basic realm=\"DVRNVRDVS\"")
                .build();

        // when
        final Request authenticated = authenticator.authenticate(null, response);

        // then
        assertThat(authenticated, is(nullValue()));
    }

    @Test
    public void testAuthenticate_withStaleNonce_shouldRetry() throws IOException {
        // given
        Request dummyRequest = new Request.Builder()
                .url("http://www.google.com")
                .header("Authorization", "Digest username=\"user1\", realm=\"myrealm\", nonce=\"AAAAAAA\", uri=\"/\", response=\"[0-9a-f]+\", qop=auth, nc=00000001, cnonce=\"[0-9a-f]+\", algorithm=MD5")
                .get()
                .build();
        Response response = new Response.Builder()
                .request(dummyRequest)
                .protocol(Protocol.HTTP_1_1)
                .code(401)
                .addHeader("WWW-Authenticate",
                        "Digest realm=\"myrealm\", nonce=\"BBBBBB\", stale=\"true\", algorithm=MD5, qop=\"auth\"")
                .addHeader("WWW-Authenticate", "Basic realm=\"DVRNVRDVS\"")
                .build();

        // when
        final Request authenticated = authenticator.authenticate(null, response);

        // then
        assertThat(authenticated.header("Authorization"),
                matchesPattern("Digest username=\"user1\", realm=\"myrealm\", nonce=\"BBBBBB\", uri=\"/\", response=\"[0-9a-f]+\", qop=auth, nc=00000001, cnonce=\"[0-9a-f]+\", algorithm=MD5"));
    }
```

**Comment by glenharris** [comment]
Sorry about that - the 'stale' code was pretty much just a guess that
passed the compile test and seemed plausible :-)

I am pretty sure you are correct - it should be looking at the response for
'Stale'.  I am unable to run any of the tests because I have hacked the
project to run in a plain java (non-android) environment.  Would you
consider a patch set that removed the android dependency (e.g. switching
out logging for slf4j/slf4j-android)?

Glen.

**Comment by rburgst** [comment]
The next version will no longer rely on android logging. See also #13

**Comment by rburgst** [comment]
latest code doesn't rely on android logging anymore, can you give it a go?

**Comment by glenharris** [comment]
Will do, however it may take a couple of days before I can get to it.

Thanks,

Glen.
