### ISSUE TITLE
OkHttp3:authenticator.setCredentials wrong

### ISSUE THREAD

**Issue by kjklmn** [rburgst/okhttp-digest#15]
client = new OkHttpClient();
        final DigestAuthenticator authenticator = new DigestAuthenticator();
        authenticator.setCredentials(new Credentials("username", "pass"));

this is your code, but authenticator don't have method "setCredentials",can you help me to solve it?

**Comment by jpstotz** [comment]
Seem like you have to specify the credentials now as a parameter for the constructor of DigestAuthenticator. You can easily see that in the source code of [DigestAuthenticator](https://github.com/rburgst/okhttp-digest/blob/946ec4f8bf4b919fa0a8eeb664be428d6ba59c00/src/main/java/com/burgstaller/okhttp/digest/DigestAuthenticator.java)

**Comment by rburgst** [comment]
you are correct. will update the docs.
