### ISSUE TITLE
Manifest shouldn't define unneeded attributes

### ISSUE THREAD

**Issue by jruesga** [rburgst/okhttp-digest#18]
Since this library doesn't required backup and doesn't made use of the use, allowBackup and supportsRtl aren't needed and cause apps importing this library to use manifest merger to replace this properties.
For allowBackup isn't currently possible becasue there is a bug that prevents to replace the library property (https://code.google.com/p/android/issues/detail?id=70073).

I fixed it here https://github.com/jruesga/okhttp-digest/commit/78fb09f993651dc26a67f1758544a021f5864b0a (and fixed other lint warnings as well). Since i modify sdk versions and the lint warnings a didn't pushed a pull request,  but i could do it easy if you one.

**Comment by rburgst** [comment]
can you send a PR, then I can merge it.

**Comment by jruesga** [comment]
https://github.com/rburgst/okhttp-digest/pull/19

**Comment by rburgst** [comment]
Thanks for the PR!
