### ISSUE TITLE
SNAPSHOT dependency

### ISSUE THREAD

**Issue by devriesb** [rburgst/okhttp-digest#3]
@rburgst,

Thanks a lot for making this project available.  We're using it in Apache NiFi, but see that you have a dependency on com.squareup.okhttp:okhttp:2.6.0-SNAPSHOT.  The most recent version of okhttp appears to be 2.7.0[1]... do you have plans to update the dependency?  Thanks again.

[1] https://github.com/square/okhttp/blob/master/CHANGELOG.md

Brandon

**Comment by rburgst** [comment]
I was waiting for 2.7.0 as I rely on a specific pull request from it. Now that it has been released I will update it in the next few days and release a new version. Thanks for pointing this out.

**Comment by devriesb** [comment]
Fantastic!  Thanks a lot.

Brandon
