### ISSUE TITLE
Does this build without Android?

### ISSUE THREAD

**Issue by sammefford** [rburgst/okhttp-digest#30]
When I downloaded the source ran with "./gradlew install" I got this:

```
* Where:
Build file 'C:\temp\okhttp-digest-1.12\okhttp-digest-1.12\build.gradle' line: 116

* What went wrong:
A problem occurred evaluating root project 'okhttp-digest-1.12'.
> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
```

I can't point it to ANDROID_HOME since I don't have android.  Can I not build or use this library without android?

**Comment by rburgst** [comment]
havent tried without android, can you try `./gradlew assemble`

**Comment by sammefford** [comment]
I get the same error as above with `./gradlew assemble`

**Comment by rburgst** [comment]
I will convert it to a pure java library.
