### ISSUE TITLE
Maven Central?

### ISSUE THREAD

**Issue by sammefford** [rburgst/okhttp-digest#38]
Now that we're using okhttp-digest, our users need to add the jcentral repository to their maven / gradle projects.  Before they could get everything from maven central.  Unfortunately, some users of our project are struggling with the requirement to add jcentral, just because it's one more step and something they haven't done before.

Is there any way okhttp-digest could also deploy to maven central?  Official instructions are [here](http://central.sonatype.org/pages/producers.html). An automated option is [here](http://www.sonatype.org/nexus/2015/01/08/deploy-to-maven-central-repository/).

**Comment by rburgst** [comment]
its a bit problematic as I would need to use a different group id when publishing to maven central. I fear that this wont make it any easier and simply add confusion.

**Comment by sammefford** [comment]
hmm, darn.  Yeah, that would be a problem.  Just curious, why would you need to use a different group id?  The id you're using, "com.burgstaller" isn't in use on maven central is it?

**Comment by rburgst** [comment]
AFAIK you need to own burgstaller.com in order to claim the group

**Comment by sammefford** [comment]
So I take it that's not your dump truck company? :)

**Comment by rburgst** [comment]
hehe, never checked that site, who knew :)
