### ISSUE TITLE
Update README.md to reflect versions beyond 1.15

### ISSUE THREAD

**Issue by jamesajones** [rburgst/okhttp-digest#40]
Update README.md to reflect usage beyond version 1.15 This should include 1.9

**Comment by rburgst** [comment]
I dont understand the description, can you please explain?

**Comment by jamesajones** [comment]
>The repo indicate current version is 1.15. I was able to get a jar of version 1.9. Tried to use the constructor DigestAuthenticator auth = new DigestAuthenticator(new Credentials ("admin", "passsword"); which was in the current repo but in Eclipse it shows as undefined.  Update README.md to reflect usage beyond version 1.15 This should include 1.9

**Comment by rburgst** [comment]
I still dont understand, on https://bintray.com/rburgst/android/okhttp-digest/1.15 there is 1.15, the readme states 1.15. The constructor you mentioned is also used in the tests and therfore works.

https://github.com/rburgst/okhttp-digest/blob/master/src/test/java/com/burgstaller/okhttp/digest/DigestAuthenticatorTest.java#L83

Make sure that you get the latest jar off of bintray.
It might help if you copy the error message of the compiler and please also double check

**Comment by rburgst** [comment]
also note that 1.15 is the latest version. 1.9 is older!

**Comment by jamesajones** [comment]
OK

**Comment by jamesajones** [comment]
Thanks got wrapped around the axle there
