### ISSUE TITLE
No v0.7 tag so not on Bintray

### ISSUE THREAD

**Issue by JPercivall** [rburgst/okhttp-digest#5]
v0.7 is listed in the release notes but it does not have a git tag associated with it so it has not been pushed out to bintray for consumption.

**Comment by JPercivall** [comment]
Do you have a link to where it should be? I tried going to: https://bintray.com/rburgst/android/okhttp-digest/0.7/view but I get a 404.

**Comment by rburgst** [comment]
0.6 is currently the latest version. I just mistyped in the Changelog.

**Comment by JPercivall** [comment]
Ah, sorry, I missed that. Thanks!
