### ISSUE TITLE
Does BasicAuthenticator.proxy cause a concurrency bug?

### ISSUE THREAD

**Issue by yschimke** [rburgst/okhttp-digest#50]
Seems like two concurrent requests could get confused

**Comment by yschimke** [comment]
Awkwardly it seems to be also how BasicAuthenticator knows how to authenticate.  Could this be avoided by using builder.proxyAuthenticator as well as builder.authenticator?

**Comment by rburgst** [comment]
you are correct and it could but it would require a more complex setup. Need to think about it. Do you have a specific case where this causes a problem?

**Comment by yschimke** [comment]
Yep - I'll link to it when it's landed.  I'm getting it working without Caching, implementing my own BasicAuthenticator for now.  Probably Kerberos next.  

Essentially this hit whenever you want to use your nice library as part of another one.  Unless you are the end user, it's hard to know whether it will need basic auth for both proxy and WWW together.

**Comment by rburgst** [comment]
any updates? Otherwise I would like to close this.

**Comment by yschimke** [comment]
Close away. No updates. Sorry
