### ISSUE TITLE
BasicAuthenticator should support a credentials lookup

### ISSUE THREAD

**Issue by yschimke** [rburgst/okhttp-digest#51]
i.e. when the client is used to connect to multiple backends.  This is possible by replacing the BasicAuthenticator, but this duplicates functionality e.g. terminating after a unsuccessful request.

**Comment by rburgst** [comment]
can you detail your idea further or submit a PR?

**Comment by yschimke** [comment]
Yep, I'll post a link when it's ready.  FWIW I've forked your library (which is great), so I can selfishly work in Kotlin.
