### ISSUE TITLE
Handling of the escape character in Digest Authentication Flow

### ISSUE THREAD

**Issue by mrunal-upadhyay** [rburgst/okhttp-digest#56]
Hey,

I was facing an issue with Digest Authentication flow if the url contains backslash in the URL.

Below is just an example:
 Request dummyRequest = new Request.Builder()
                .url("http://www.google.com?arg1=\&arg2=1892825586")
                .get()
                .build();

There seems to be some issue in encoding decoding the uri if the url contains backslash(\)

**Comment by rburgst** [comment]
can you be more precise on what issue you are seeing?
Also note that \ is not a valid URL char: 
https://stackoverflow.com/questions/7109143/what-characters-are-valid-in-a-url

**Comment by rburgst** [comment]
closed due to no response
