### ISSUE TITLE
Explain how to run ProxyAuthenticationManualTest

### ISSUE THREAD

**Issue by ghostbuster91** [rburgst/okhttp-digest#58]
Hi,

Am writing a similar feature in [sttp](https://github.com/softwaremill/sttp) project and it would be great if you can share what you used as a proxy for ProxyAuthenticationManualTest.

**Comment by rburgst** [comment]
Wow, this was a long time ago. I have wiped my machine a couple of times since then. From the old pcap files I can only tell you that I was using squid. I no longer have the exact configuration that I used back then. Sorry.

**Comment by ghostbuster91** [comment]
Ok, thanks for the response. I will leave the issue open for now, since I will try to create something similar and may use your project to test it. If I succeed I will post some tips here, is this ok for u?

**Comment by rburgst** [comment]
I would encourage you to do that. I can then add the instructions either to the readme or the test.

**Comment by ghostbuster91** [comment]
Better late than never :) https://github.com/softwaremill/sttp/blob/master/manual-tests/proxy-digest-test.md 

I see that you already linked some how-to article. Feel free to close this issue then ;)
