### ISSUE TITLE
Error code 401

### ISSUE THREAD

**Issue by GreenSnakeLinux** [rburgst/okhttp-digest#61]
Hello,

I've got an error 401 with following code:
[https://stackoverflow.com/questions/59630599/android-java-do-digest-authentication-with-okhttp-and-okhttp-digest-error-co](https://stackoverflow.com/questions/59630599/android-java-do-digest-authentication-with-okhttp-and-okhttp-digest-error-co) 

Maybe i've done something wrong, but i have respected the exemple in main page. Thanks for your help.

**Comment by rburgst** [comment]
1. try and use a known working client and capture the http traffic
2. check `com.burgstaller.okhttp.digest.DigestAuthenticatorTest#testWWWAuthenticate__withUriPathAndParameters` and inject the observed values into the test and see whether the library creates the correct authorization header.

**Comment by GreenSnakeLinux** [comment]
user / password was set with HttpUrlConnection so i switch to OkHttp and now I've got the familiar error :
[java.io.IOException: unexpected end of stream](https://stackoverflow.com/questions/55950254/retrofit-okhttp-unexpected-end-of-stream-on-connection-error)
From what I understand the error is from OkHttp, I need to wait a potential correction. I'll stay with HttpUrlConnection in the mean time.

**Comment by rburgst** [comment]
As the SO post hints unexpected end of stream means that your server is sending an invalid response with a wrong content-length header. This has nothing to do with authentication.
As stated earlier the best advice I can offer is to capture the http traffic from HttpUrlConnection (i.e. by using a proxy such as Fiddler or CharlesProxy) and then check the difference between the two. You can then re-create the problem in the unit test `com.burgstaller.okhttp.digest.DigestAuthenticatorTest#testWWWAuthenticate__withUriPathAndParameters`

**Comment by GreenSnakeLinux** [comment]
Ok thanks. Before doing this, is there a way to bypass or override the check lenght since I cannot update the server (it's a Smart TV) ?

**Comment by rburgst** [comment]
you would need to check with the `okhttp` guys. This has nothing to do with `okhttp-digest`.
