### ISSUE TITLE
How to use UTF-8 in basic and digest access authentication

### ISSUE THREAD

**Issue by SailReal** [rburgst/okhttp-digest#66]
`okhttp` does support providing [different char-sets for authentication](https://github.com/square/okhttp/blob/930a8aeee2f659855ec9426bc31863d8540babc4/okhttp/src/main/kotlin/okhttp3/Credentials.kt#L28). Using the default of `okhttp` which is `ISO_8859_1` I've problems with some servers and chars e.g. "äöü" and want to switch to `UTF-8`.

How can I archive this using basic and digest access authentication and this library?

https://github.com/rburgst/okhttp-digest/blob/1e271666fbeb42f1e1f9520cc1f48b8826244ad2/src/main/java/com/burgstaller/okhttp/basic/BasicAuthenticator.java#L42

If I provide the authentication directly to `okhttp` using `UTF-8` my Nextcloud accepts chars like "äöü" in the password.
```java
.authenticator((route, response) -> {
    String credential = okhttp3.Credentials.basic("test", "äöüäöüäöü", UTF_8);
    return response.request().newBuilder().header("Authorization", credential).build();
})
```

**Comment by rburgst** [comment]
https://stackoverflow.com/questions/7242316/what-encoding-should-i-use-for-http-basic-authentication

**Comment by rburgst** [comment]
hm, will check this. Sorry, didnt read the 2nd part of your ticket.

**Comment by SailReal** [comment]
> hm, will check this. Sorry, didnt read the 2nd part of your ticket.

Thanks, if you need further information or a test account please let me know.

**Comment by rburgst** [comment]
released 2.4 which adds the ability to provide the charset.

**Comment by SailReal** [comment]
Woooow impressive, thanks for the quick implementation :rocket:!

I have already tested it, it works, thanks!

Can you please add it for digest access authentication too?

**Comment by SailReal** [comment]
@rburgst is there a chance that the `UTF-8` charset finds a way also in the [DigestAuthenticator](https://github.com/rburgst/okhttp-digest/blob/master/src/main/java/com/burgstaller/okhttp/digest/DigestAuthenticator.java#L96)?

**Comment by rburgst** [comment]
@SailReal okhttp-digest is currently a straight up port of https://github.com/apache/httpcomponents-client/blob/master/httpclient5/src/main/java/org/apache/hc/client5/http/impl/auth/DigestScheme.java, does it work with apache HC?
