### ISSUE TITLE
Failed to resolve: com.burgstaller:okhttp-digest:1.19

### ISSUE THREAD

**Issue by emauro** [rburgst/okhttp-digest#67]
After I updated to Android Studio 4 I can't compile my project due this error. If I downgrade to version 1.18 it compiles. And I receive an alert that there is newer version available (1.19). 

Does anyone know how to solve it?

**Comment by rburgst** [comment]
you are correct. there seems to be something wrong with this release, however, I didnt do anything different. Is there a reason why you dont use 2.3?

**Comment by rburgst** [comment]
the files are available, hmm

https://jcenter.bintray.com/com/burgstaller/okhttp-digest/1.9/

**Comment by rburgst** [comment]
I have release 1.20 with the same code as 1.19, this seems to work. Probably a bug in bintray. 
You might want to upgrade to 2.3 though.
