### ISSUE TITLE
How to use OkHttp 3.12.x which supports API level 9+ in okhttp-digest

### ISSUE THREAD

**Issue by SailReal** [rburgst/okhttp-digest#68]
From https://square.github.io/okhttp/
> The OkHttp 3.12.x branch supports Android 2.3+ (API level 9+) and Java 7+. These platforms lack support for TLS 1.2 and should not be used. But because upgrading is difficult we will backport critical fixes to the 3.12.x branch through December 31, 2021.

Our app targets API level 18. This library currently supports only the main OkHttp 4.x branch. Would it be possible to provide a variant which can be used when targeting API level 9+?

```
implementation com.squareup.okhttp3:okhttp:3.12.12
implementation(com.burgstaller:okhttp-digest:2.4) {
	exclude group: 'com.squareup.okhttp3', module: 'okhttp'
}
```

Excluding OkHttp from okhttp-digest and using OkHttp 3.12.12 directly will cause runtime crashes with cause `No field INSTANCE of type Lokhttp3/internal/http/RequestLine; in class Lokhttp3/internal/http/RequestLine`

**Comment by rburgst** [comment]
use the 1.x branch for older okhttp

**Comment by SailReal** [comment]
Thanks for the fast response!

Am I correct in assuming that changes like https://github.com/rburgst/okhttp-digest/issues/66 are not reflected in the 1.x branch?

**Comment by rburgst** [comment]
that is correct. feel free to create a PR
