### ISSUE TITLE
Jcenter closing in May

### ISSUE THREAD

**Issue by Tolriq** [rburgst/okhttp-digest#71]
Hi,

Thanks for your library. 
As you may already know JCenter will close in May and your library is only present there. 
Do you have any plans to migrate this library to Maven or some other place?

Regards,
Tolriq

**Comment by rburgst** [comment]
Thanks for letting me know. Yes, I do plan to migrate, most likely to maven central, however, the coordinates will most likely change since I dont own burgstaller.com.

**Comment by rburgst** [comment]
see https://issues.sonatype.org/browse/OSSRH-64413

**Comment by Tolriq** [comment]
Hi, yes this is the case for many :(
It's only problematic for predictable rebuild of earlier versions.
But it's still possible to build locally and use those old versions. Lot's of work, but well no real choice after JCenter move :(

Thanks for taking care of this.

**Comment by rburgst** [comment]
the artifact should now be available at the maven central coordinates: `io.github.rburgst:okhttp-digest:2.5`

**Comment by Tolriq** [comment]
Works thanks.
