### ISSUE TITLE
After putting app idle for some time it gives 401 issue for authorised request

### ISSUE THREAD

**Issue by sayali-mane** [rburgst/okhttp-digest#76]
This is library logs - After updating the library still it giving this issue  implementation('io.github.rburgst:okhttp-digest:2.5') 

previous digest authentication with same nonce failed, returning null
Cached authentication expired. Sending a new request.
previous digest authentication with same nonce failed, returning null

is there any workaround?

**Comment by rburgst** [comment]
Are you certain that you are using the correct password? I would also recommend to add 

https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor

to see whats actually going on.

**Comment by sayali-mane** [comment]
Yes, Password is correct - My scenario is 
When I logged into my application and start using it there won't be any problem.
All request gives me proper response.
But If I kept my app idle for some time -> then API thows 401 error and after checking the logs I found above error.


Also I am aready using https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor this for logs from that only I got this error.

**Comment by rburgst** [comment]
in that case it seems that your server has some kind of session timeout and a re-authentication is probably expected.
At any rate I dont think this has anything to do with `okhttp-digest`.

**Comment by sayali-mane** [comment]
Actually I debug all the things and then I have repo - like
1. server key expiry time is 1year
2. and session expiration time is also 24hours
And by above log previous digest authentication with same nonce failed, returning null
I found from lib class

**Comment by sayali-mane** [comment]
my issue is similar to [](https://github.com/rburgst/okhttp-digest/issues/63)

**Comment by rburgst** [comment]
I am unsure of how I can help here without getting detailed logs.

If you suspect that the error is in okhttp-digest, then I urge you to create a unit test that shows the problem or you post the detailed logs with the http traffic (you might need to scan the log and remove any personal information as well as hints to the authentication).
