### ISSUE TITLE
Are the `com.burgstaller:okhttp-digest` artifacts hosted on any public repo?

### ISSUE THREAD

**Issue by sidesho96** [rburgst/okhttp-digest#81]
Hi, I've run into an issue where my Gradle project cannot resolve the dependency on `com.burgstaller:okhttp-digest:1.10` when loading an Asciidoc plugin.  This issue presented itself yesterday after working the day before without any project changes.  (Note:  The pipeline used doesn't cache dependencies, so the project retrieves plugins and dependencies for each run.)

```
Could not find com.burgstaller:okhttp-digest:1.10.

Searched in the following locations:

- https://plugins.gradle.org/m2/com/burgstaller/okhttp-digest/1.10/okhttp-digest-1.10.pom
- https://repo.maven.apache.org/maven2/com/burgstaller/okhttp-digest/1.10/okhttp-digest-1.10.pom

Required by:

project :docs > org.asciidoctor.jvm.gems:org.asciidoctor.jvm.gems.gradle.plugin:3.3.2 > org.asciidoctor:asciidoctor-gradle-jvm-gems:3.3.2 > com.github.jruby-gradle:jruby-gradle-core-plugin:2.0.2 > io.github.http-builder-ng:http-builder-ng-okhttp:1.0.3
```

Is there a public repository where I can still resolve `com.burgstaller:okhttp-digest:1.10`? 

-Thanks

**Comment by rburgst** [comment]
Please check the section marked "important" in the readme. com.burgstaller was the old coordinates before I had to move to maven central.

**Comment by rburgst** [comment]
Yes the com.burgstaller artifacts we're on jcenter.

**Comment by sidesho96** [comment]
I appreciate your patience and quick responses, and I apologize for any time of yours I've wasted. 

It turns out [Jcenter was down and/or forwarding artifact requests to Maven Central for a couple days](https://status.gradle.com). 

Best Regards.

**Comment by sidesho96** [comment]
I'm not sure which disposition is the most appropriate for closing this issue, so I'll leave that for you if that's okay.

**Comment by MarkBenjaminKatamba** [comment]
See my comment on a similar issue here: https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/679#issuecomment-2252292062. 

> Hi, I've run into an issue where my Gradle project cannot resolve the dependency on `com.burgstaller:okhttp-digest:1.10` when loading an Asciidoc plugin. This issue presented itself yesterday after working the day before without any project changes. (Note: The pipeline used doesn't cache dependencies, so the project retrieves plugins and dependencies for each run.)
> 
> ```
> Could not find com.burgstaller:okhttp-digest:1.10.
> 
> Searched in the following locations:
> 
> - https://plugins.gradle.org/m2/com/burgstaller/okhttp-digest/1.10/okhttp-digest-1.10.pom
> - https://repo.maven.apache.org/maven2/com/burgstaller/okhttp-digest/1.10/okhttp-digest-1.10.pom
> 
> Required by:
> 
> project :docs > org.asciidoctor.jvm.gems:org.asciidoctor.jvm.gems.gradle.plugin:3.3.2 > org.asciidoctor:asciidoctor-gradle-jvm-gems:3.3.2 > com.github.jruby-gradle:jruby-gradle-core-plugin:2.0.2 > io.github.http-builder-ng:http-builder-ng-okhttp:1.0.3
> ```
> 
> Is there a public repository where I can still resolve `com.burgstaller:okhttp-digest:1.10`?
> 
> -Thanks

See my comment here: https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/679#issuecomment-2252292062, I found another url to what seems to be a public repo where you can resolve `com.burgstaller:okhttp-digest:1.10`. Adding that url to the repositories block inside gradle.build file helped resolve the issue for me.

**Comment by h1romas4** [comment]
I have the same problem and have also found that the Apache Archiva redirects are not working correctly.

> https://attic.apache.org/projects/archiva.html
>
> [Apache Archiva](https://archiva.apache.org/) moved into the Attic in 2024-02. Apache Archiva mission was the creation and maintenance of software related to Build Artifact Repository Manager.

I responded as follows in the workaround. It seems to work anyway, even though okhttp-digest is not the same version as the dependencies.

`build.gradle`

```
buildscript {
    configurations.classpath {
        resolutionStrategy.dependencySubstitution {
            // https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/679#issuecomment-2371010585
            // fix dependencies (Could not find io.github.rburgst:okhttp-digest:1.10)
            substitute module('com.burgstaller:okhttp-digest') using module('io.github.rburgst:okhttp-digest:1.21')
        }
    }
}

plugins {
    id 'org.asciidoctor.jvm.convert' version '3.3.2'
    id 'org.asciidoctor.jvm.pdf' version '3.3.2'
    id 'org.asciidoctor.jvm.gems' version '3.3.2'
}
```
