### ISSUE TITLE
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is **java.lang.IncompatibleClassChangeError**:  Expected static method okhttp3.internal.http.RequestLine.requestPath(Lokhttp3/HttpUrl;)Ljava/lang/String;

### ISSUE THREAD

**Issue by pandurangnawale** [rburgst/okhttp-digest#84]
**It was working fine with gradle version 6.5 and okhttp3 : 3.14.4.
After upgrading gradle version 8.1.1 and okhttp3 version 4.11.0 getting below exception** 

"org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is **java.lang.IncompatibleClassChangeError**: 
Expected static method okhttp3.internal.http.RequestLine.requestPath(Lokhttp3/HttpUrl;)Ljava/lang/String;
org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1087)
org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) 
org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) 
javax.servlet.http.HttpServlet.service(HttpServlet.java:517) 
org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) 
org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1656) 
org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:292) 
org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) 
org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1626) 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:337) 
org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:115) 
org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:81) 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) 
org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:122) 
org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:116) 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) 
org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:126) 
org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:81) 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) 
org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:109) 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) 
org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:149) 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) 
org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) 
org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) 
org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346) 
org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:223) 
org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217)

**Comment by rburgst** [comment]
which version of `okhttp-digest` are you using? ensure you are on the latest version.

**Comment by rburgst** [comment]
also the fact that okhttp-digest is not on the stack trace makes me believe that it has nothing to do with your problem.

**Comment by pandurangnawale** [comment]
I am using okhttp-digest version 0.4.0

**Comment by rburgst** [comment]
only the latest version is compatible with okhttp 4.11

**Comment by pandurangnawale** [comment]
Yes. I am using latest version of both lib.
okhttp3 - 4.11.0
okhttp-digest - 0.4.0

**Comment by pandurangnawale** [comment]
After upgrading 
'com.baulsupp:okhttp-digest:0.4.0'  to  'io.github.rburgst:okhttp-digest:3.1.0' working fine.
