### ISSUE TITLE
Version 1.10 of published artifact is gone

### ISSUE THREAD

**Issue by lstreepy** [rburgst/okhttp-digest#86]
It appears that version 1.10 of the `okhttp-digest` jar (at [com.burgstaller](https://mvnrepository.com/artifact/com.burgstaller) » okhttp-digest) has been removed (or is no longer accessible) from Maven Central.

I don't know if this is the correct place to report this, but this situation is breaking a ton of our projects because we use the HTTP Gradle plugin (https://http-builder-ng.github.io/gradle-http-plugin/), and it has a transitive dependency on `io.github.http-builder-ng:http-builder-ng-okhttp:1.0.3` which relies on your library.

Can you please restore this artifact?

**Comment by rburgst** [comment]
Hi, thanks for your report. The problem is that the artifact with the `com.burgstaller.okhttp-digest` coordinates was hosted on bintray which has been abandoned a long time ago. 
Therefore, the component is only available on maven central under https://mvnrepository.com/artifact/io.github.rburgst/okhttp-digest, please inform the maintainer of https://http-builder-ng.github.io/gradle-http-plugin/ about the coordinate change. Also note that 1.10 is pretty ancient, I really recommend upgrading to current versions of the library.
See also #71 .
Note that the change happened already in 2021.

**Comment by lstreepy** [comment]
Thank you.  After more research, we found what you stated above.  Our predicament was due to using an old Gradle plugin that had ok-http as a transitive dependency, and it has a dependency on your artifact.  No newer version of the plugin is available, but we have managed to rework our Gradle plugin to rely on Apache http instead and remove the need for ok-http.

Thank you for your quick response.

**Comment by amydoxym** [comment]
hey @lstreepy ! We are having the same isssue with one of our Gradle plugin
 `org.asciidoctor.jvm.gems:org.asciidoctor.jvm.gems.gradle.plugin:3.3.2 > org.asciidoctor:asciidoctor-gradle-jvm-gems:3.3.2 > com.github.jruby-gradle:jruby-gradle-core-plugin:2.0.2 > io.github.http-builder-ng:http-builder-ng-okhttp:1.0.3 > com.burgstaller:okhttp-digest:1.10`

How did you solve your issue please?

**Comment by lstreepy** [comment]
Sadly, the only option I could find was to rip out my implementation using
the plugin that pulled in
io.github.http-builder-ng:http-builder-ng-okhttp   and
rewrite it using a newer library (Apache HTTP Client 5).

Larry.

**Comment by psathuluri** [comment]
I have a similar issue where my project was using asciidoctor-gradle-plugin which has a transitive dependency `com.burgstaller:okhttp-digest:1.10`. [This comment](https://github.com/asciidoctor/asciidoctor-gradle-plugin/issues/731#issuecomment-2233782799) works for me as a stopgap - adding the following to the build script:

```
buildscript {
    configurations.classpath {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            if (details.requested.group == 'com.burgstaller' && details.requested.name == 'okhttp-digest' && details.requested.version == '1.10') {
                details.useTarget "io.github.rburgst:${details.requested.name}:1.21"
                details.because 'Dependency has moved'
            }
        }
    }
}
```

**Comment by amydoxym** [comment]
Thanks @psathuluri ! Will try this out
